# Generated by Django 4.1.1 on 2022-09-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jsondatas',
            fields=[
                ('assid', models.AutoField(primary_key=True, serialize=False)),
                ('end_year', models.IntegerField()),
                ('intensity', models.IntegerField()),
                ('sector', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('insight', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('start_year', models.IntegerField()),
                ('impact', models.CharField(max_length=255)),
                ('added', models.DateTimeField()),
                ('published', models.DateTimeField()),
                ('country', models.CharField(max_length=255)),
                ('relevance', models.IntegerField()),
                ('pestle', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('likelihood', models.IntegerField()),
            ],
        ),
    ]
