# Generated by Django 4.1.1 on 2022-09-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondatas',
            name='added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jsondatas',
            name='published',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
